name: "co2_case"
version: "1.0.0"
config-version: 2

profile: "co2_case"

model-paths: ["models"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  co2_case:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
